### ISSUE TITLE
authentication patch

### ISSUE THREAD

**Issue by ghost** [Project-Earth-Team/PatcherApp#3]
uhm can a authentication patch be implemented too as otherwise the sunset patch doesnt make it go futher then it already went

**Comment by LukeFZ** [comment]
A patch to redirect the playfab server, which is used for login, is not something possible through the patcher app. The game gets its server address through the normal game API - it isn't hardcoded in the app itself, so it cannot be patched.

**Comment by ghost** [comment]
wait so that means its a api issue

**Comment by rtm516** [comment]
The client pings out to the api to get the information for the playfab login, so you just need to configure your instance of the API to point at a valid playfab.
